### ISSUE TITLE
iOS 6 betas

### ISSUE THREAD

**Issue by JonathanSeals** [erica/ibrowser#1]
It's broken on iOS 6/Xcode 4.5 :(

**Comment by erica** [comment]
It ran for me -- could be that I haven't pushed the latest. If I get some time, I'll try to upload newer version

**Comment by erica** [comment]
Just FYI, the reason it's a bit of a pain to update is because of the zip integration -- if I didn't have dependencies, it would be up there now

**Comment by JonathanSeals** [comment]
Alright. Thanks for the quick response! The problem for me was it'd open and just hang while loading :(

**Comment by erica** [comment]
I uploaded a compiled version here: https://github.com/erica/ibrowser/downloads  Just self-sign it and install and let me know if that works for you

**Comment by JonathanSeals** [comment]
Alright, will do

**Comment by JonathanSeals** [comment]
Still hangs :(

**Comment by erica** [comment]
Skype? ericasadun

**Comment by JonathanSeals** [comment]
I'll be back at my Mac in a few hours

**Comment by erica** [comment]
I'll be back on Mommy duty then, alas. I may be in #iphonedev on freenode this evening though

**Comment by JonathanSeals** [comment]
I'm almost always in #JailbreakQA on freenode so that shouldn't be a problem.

**Comment by erica** [comment]
What nick?

**Comment by JonathanSeals** [comment]
JonSeals

**Comment by Nkapoor124** [comment]
Will the new iBrowser for iOS 6 be released soon? Thanks.

**Comment by erica** [comment]
I've got to figure out what to do about the zip stuff
